### ISSUE TITLE
Validator does not detect `duplicate` keys

### ISSUE THREAD

**Issue by gptsarthak** [sankalpmukim/cryptic-hunt-json-validation#1]
MRE:
```json
{
    "name": "Phase 1-7",
    "description": {
        "Question": "A World of Mystery", 
        "Difficulty": "Medium", 
        "Authors": [
            "Achintya Nigam"
        ]
    },
    "phase": 2,
    "isQR": false,
    "qrLink": [],
    "question": {
        "title": "A World Of Mystery",
        "description": "Clues all around, but what is the answer? A world of mystery it is. visit: a-world-of-mystery.great-site.net or https://achintyanigam.github.io to get started",
        "answer": "fincrypt",
        "pointsAwarded": 200,
        "costofHint": 50,
        "hint": "the enigma machine",
        "hint": "https://stegonline.georgeom.net/upload extract 7 Red",
        "images": [
            "https://drive.google.com/file/d/1e1zwIXwpbwGSay8bGb14On8jebGNyj5n/view?usp=sharing"
        ]
    }
}
```
Here `hint` is a duplicate key, but the validator says that the schema is valid.
It should give a nice error message like ```Duplicate keys found for "hint", each key within an object must be unique```.

**Comment by sankalpmukim** [comment]
Fair point, the zod validation does not however, it's built using monaco editor that's running a json validation engine in itself.
![image](https://github.com/sankalpmukim/cryptic-hunt-json-validation/assets/41541375/8478bcd2-b52b-42ed-b900-069a8d59f4db)

![image](https://github.com/sankalpmukim/cryptic-hunt-json-validation/assets/41541375/87039b52-8ad1-4a0a-bb51-3cfd33e80a72)
